export const commonIngredients = [
  // Proteins
  "chicken breast",
  "chicken thighs",
  "ground beef",
  "ground turkey",
  "pork chops",
  "salmon",
  "shrimp",
  "tofu",
  "eggs",
  "bacon",
  "sausage",
  "beef steak",
  "ground pork",
  "tuna",

  // Dairy
  "milk",
  "butter",
  "cheese",
  "cheddar cheese",
  "mozzarella cheese",
  "parmesan cheese",
  "cream cheese",
  "sour cream",
  "yogurt",
  "heavy cream",

  // Vegetables
  "onion",
  "garlic",
  "tomato",
  "bell pepper",
  "carrot",
  "celery",
  "broccoli",
  "spinach",
  "lettuce",
  "cucumber",
  "zucchini",
  "mushrooms",
  "potato",
  "sweet potato",
  "green beans",
  "corn",
  "peas",
  "cabbage",
  "kale",
  "eggplant",
  "cauliflower",
  "asparagus",
  "brussels sprouts",
  "avocado",
  "jalapeño",

  // Fruits
  "lemon",
  "lime",
  "apple",
  "banana",
  "orange",
  "strawberries",
  "blueberries",
  "tomatoes",

  // Grains & Pasta
  "rice",
  "pasta",
  "spaghetti",
  "penne",
  "bread",
  "flour",
  "quinoa",
  "couscous",
  "oats",
  "tortillas",

  // Canned/Packaged
  "canned tomatoes",
  "tomato paste",
  "tomato sauce",
  "chicken broth",
  "beef broth",
  "vegetable broth",
  "coconut milk",
  "black beans",
  "chickpeas",
  "kidney beans",

  // Oils & Condiments
  "olive oil",
  "vegetable oil",
  "soy sauce",
  "vinegar",
  "balsamic vinegar",
  "honey",
  "maple syrup",
  "mustard",
  "mayonnaise",
  "ketchup",
  "hot sauce",
  "worcestershire sauce",
  "fish sauce",
  "sesame oil",

  // Herbs & Spices
  "salt",
  "black pepper",
  "paprika",
  "cumin",
  "chili powder",
  "oregano",
  "basil",
  "thyme",
  "rosemary",
  "parsley",
  "cilantro",
  "ginger",
  "cinnamon",
  "nutmeg",
  "curry powder",
  "red pepper flakes",
  "garlic powder",
  "onion powder",
  "italian seasoning",

  // Nuts & Seeds
  "almonds",
  "walnuts",
  "peanuts",
  "cashews",
  "sesame seeds",
  "sunflower seeds",

  // Baking
  "sugar",
  "brown sugar",
  "baking powder",
  "baking soda",
  "vanilla extract",
  "cocoa powder",
  "chocolate chips",
].sort();
